Repository UltiMafia/Ultimafia, pull requests merged in 2023-06, with the labels that each got.

#374 added :rawr: emote
  react_main/public/images/emotes/rawr.png
  react_main/src/components/Emotes.jsx
Labels: assets

#375 Added a legacy role-icon for Host in Ghost
  react_main/public/images/roles.png
  react_main/src/css/roles.css
Labels: assets

#373 Add prettier workflow
  .github/workflows/prettier.yml
  .github/workflows/test.yml
Labels: devops

#377 feat: anonymous decks routes and schema
  Games/core/Game.js
  Games/core/Player.js
  app.js
  data/constants.js
  db/schemas.js
  react_main/src/pages/Play/AnonymousDecksSelector/AnonymousDeckSelector.jsx
  react_main/src/pages/Play/Host/Host.jsx
  react_main/src/pages/Play/Host/HostGhost.jsx
  react_main/src/pages/Play/Host/HostMafia.jsx
  react_main/src/pages/Play/Host/HostResistance.jsx
  react_main/src/pages/Play/Play.jsx
  react_main/src/pages/User/AnonymousDeckEditor.jsx
  react_main/src/pages/User/User.jsx
  routes/anonymousDeck.js
  routes/game.js
  routes/shop.js
Labels: enhancement, game/core

#372 Linchpin & President Rework
  Games/types/Mafia/roles/Village/President.js
  Games/types/Mafia/roles/cards/ElectionResults.js
  Games/types/Mafia/roles/cards/KillAlignedOnDeath.js
  react_main/src/css/roles.css
Labels: game/mafia, refactor

#381 Add prettier workflow
  .github/workflows/prettier.yml
Labels: devops

#384 Fix prettier workflow
  .github/workflows/prettier.yml
Labels: devops

#383 fixes: prophet rework, leave message consistent with join, remove taichi as ghost word, lobby rehost checks for mafia type
  Games/core/Game.js
  Games/core/Player.js
  Games/types/Ghost/Game.js
  Games/types/Ghost/data/words.js
  Games/types/Mafia/roles/cards/Prognosticate.js
  Games/types/Mafia/roles/cards/WinIfPrescient.js
  data/roles.js
  react_main/src/pages/Play/Host/HostGhost.jsx
  react_main/src/pages/Play/Join.jsx
Labels: bug

#382 fix(ui): add correction code for wrong role group count
  react_main/src/pages/Play/CreateSetup/CreateSetup.jsx
  react_main/src/pages/Play/Host/Host.jsx
Labels: bug, frontend/ui

#366 feat(mafia): Quack, Friendly+Preoccupied Mods
  Games/types/Mafia/Action.js
  Games/types/Mafia/roles/Mafia/Quack.js
  Games/types/Mafia/roles/cards/BlockIfVisited.js
  Games/types/Mafia/roles/cards/BlockTargets.js
  Games/types/Mafia/roles/cards/PsychesSenses.js
  Games/types/Mafia/roles/cards/TrackPlayer.js
  Games/types/Mafia/roles/cards/WaddleAndTellSecret.js
  data/constants.js
  data/roles.js
  react_main/src/pages/Learn/LearnMafia.jsx
Labels: game/mafia

#422 Add Grouch
  Games/types/Mafia/roles/Independent/Grouch.js
  Games/types/Mafia/roles/cards/WinIfAliveWhenVillageLose.js
  data/roles.js
Labels: game/mafia

#442 fix: message.content.indexOf not found
  react_main/src/pages/Game/Game.jsx
Labels: bug, frontend/ui
