Repository UltiMafia/Ultimafia, pull requests merged in 2023-07, with the labels that each got.

#448 modified slang list
  react_main/src/json/slangList.js
Labels: frontend/ui

#446 Improving SEO
  Games/core/Agora.js
  Games/core/Meeting.js
  react_main/package-lock.json
  react_main/package.json
  react_main/public/index.html
  react_main/src/pages/Game/Game.jsx
  react_main/src/pages/Game/GhostGame.jsx
  react_main/src/pages/Game/MafiaGame.jsx
  react_main/src/pages/Game/OneNightGame.jsx
  react_main/src/pages/Game/ResistanceGame.jsx
  react_main/src/pages/Game/SplitDecisionGame.jsx
Labels: frontend/ui, refactor, site/general

#432 added vain and weak
  Games/types/Mafia/roles/cards/Vain.js
  Games/types/Mafia/roles/cards/Weak.js
  data/constants.js
  react_main/src/pages/Learn/LearnMafia.jsx
Labels: enhancement, game/mafia

#463 docs: fix broken images
  docs/guide-role-icons.md
  docs/setup-beginner-guide.md
  docs/setup-bot-games.md
  docs/setup-dependencies.md
Labels: documentation

#466 removed fly
  Games/types/Mafia/roles/Village/Fly.js
  Games/types/Mafia/roles/cards/EavesdropOnEvils.js
  data/roles.js
Labels: game/mafia, refactor

#471 fix(ghost): do not pass microphone if game has ended
  Games/types/Ghost/Game.js
Labels: bug, game/other

#472 fix: roleplay lobby checks
  react_main/src/pages/Play/Host/HostGhost.jsx
  react_main/src/pages/Play/Host/HostJotto.jsx
  react_main/src/pages/Play/Host/HostOneNight.jsx
  react_main/src/pages/Play/Host/HostResistance.jsx
  react_main/src/pages/Play/Host/HostSplitDecision.jsx
  routes/game.js
Labels: bug

#477 ui: add more than 10 icons, mostly vivid
  react_main/public/images/roles/actress-vivid.png
  react_main/public/images/roles/bluebeards-wife-vivid.png
  react_main/public/images/roles/bride-vivid.png
  react_main/public/images/roles/celebrity-vivid.png
  react_main/public/images/roles/eve-vivid.png
  react_main/public/images/roles/fool-vivid.png
  react_main/public/images/roles/gambler-vivid.png
  react_main/public/images/roles/granny-vivid.png
  react_main/public/images/roles/gunslinger-noir.png
  react_main/public/images/roles/gunslinger-vivid.png
  react_main/public/images/roles/heartbreaker-noir.png
  react_main/public/images/roles/hooker-vivid.png
  react_main/public/images/roles/housekeeper-vivid.png
  react_main/public/images/roles/janitor-vivid.png
  react_main/public/images/roles/king-vivid.png
  react_main/public/images/roles/lover-vivid.png
  react_main/public/images/roles/medium-vivid.png
  react_main/public/images/roles/mindwarper-noir.png
  react_main/public/images/roles/mourner-vivid.png
  react_main/public/images/roles/necromancer-vivid.png
  react_main/public/images/roles/nomad-vivid.png
  react_main/public/images/roles/oracle-vivid.png
  react_main/public/images/roles/psyche-vivid.png
  react_main/public/images/roles/sapling-vivid.png
  react_main/public/images/roles/siren-vivid.png
  react_main/public/images/roles/town-crier-vivid.png
  react_main/public/images/roles/traitor-vivid.png
  react_main/public/images/roles/tree-vivid.png
  react_main/public/images/roles/villager-vivid.png
  react_main/public/images/roles/virgin-vivid.png
  react_main/public/images/roles/waitress-vivid.png
  react_main/public/images/roles/yakuza-vivid.png
  react_main/src/css/roles.css
Labels: frontend/ui

#546 Added github, patreon, kofi links
  react_main/public/images/kofi.png
  react_main/src/Main.jsx
  react_main/src/css/main.css
Labels: enhancement, site/general

#547 Allow use of latest node version
  react_main/package.json
Labels: enhancement

#597 added three new game icons for lobby UI
  react_main/public/images/games.png
  react_main/src/css/setup.css
Labels: assets
